spring.application.name=flightreservation

spring.datasource.url=jdbc:mysql://localhost:3306/reservation
spring.datasource.username=root
spring.datasource.password=7462802416@mK

spring.jpa.show-sql=true
#spring.servlet.context-path=/reservation

spring.thymeleaf.cache=false
spring.jpa.hibernate.ddl-auto=update


# SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Your Gmail (sender email)
spring.mail.username=davidrnms@gmail.com

# App Password (NOT your normal Gmail password)
spring.mail.password=xxxxxxxxxxxxxx

# Protocol settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#logging.level.root=INFO
#logging.file.name=/Users/manishkumar/Documents/flightreservation_logs/reservation.log

com.manish.flightreservation.itinerary.dirpath=/Users/manishkumar/Documents/flightReservation/reservation
com.manish.flightreservation.itinerary.email.subject=Booking for your Flight
com.manish.flightreservation.itinerary.email.body=Please find your Itinerary attached.

