gg.jte.development-mode=true
spring.application.name=flightcheckin
# ===============================
# SERVER CONFIG
# ===============================
server.port=8081
server.servlet.context-path=/flightcheckin

## ===============================
## VIEW RESOLVER (JSP CONFIG)
## ===============================
#spring.mvc.view.prefix=/WEB-INF/jsps/
#spring.mvc.view.suffix=.jsp

## ===============================
## RESERVATION SERVICE (INTEGRATION)
## ===============================
## URL of Flight Reservation microservice
#reservation.service.url=http://localhost:8080/flightreservation

